### ISSUE TITLE
datatable在手机上展示，那效果....

### ISSUE THREAD

**Issue by xfworld** [amazeui/datatables#1]
我把datatable放在一个panel里面，如果将布局改为<code>am-u-md-6</code>，在pc端显示效果.......太坑
![qq 20150605105047](https://cloud.githubusercontent.com/assets/5020771/7998593/c84a33d4-0b70-11e5-99c1-99e3a990338e.png)

手机端看到的效果和这个类似.... 咋优化...

**Comment by Minwe** [comment]
加了响应式的例子了。

**Comment by xfworld** [comment]
@Minwe tab选项卡能不能也优化下，加个响应式的例子... 现在感觉特猥琐....

**Comment by Minwe** [comment]
Tabs 本来就是响应式，具体有什么问题你在 allmobilize/amazeui/issues/602 那边说就行了。

**Comment by xfworld** [comment]
不知道为什么图片上传老报错，吐血...

**Comment by Minwe** [comment]
GitHub 用的 S3 存图片，传图的时候最好开着梯子。

**Comment by xfworld** [comment]
![qq 20150605153413](https://cloud.githubusercontent.com/assets/5020771/8001672/727b955e-0b9a-11e5-8bd8-c9385f8f1f58.png)

终于传上来了，你看看分页的导航条。
另外我把浏览器缩小后，响应式就启用了，然后在最大化，响应式没有把table还原。一会上图

**Comment by xfworld** [comment]
这是初始化的效果
![tabley](https://cloud.githubusercontent.com/assets/5020771/8001750/38963078-0b9b-11e5-99b5-c39640761b3a.png)
这是缩小的效果
![tableb](https://cloud.githubusercontent.com/assets/5020771/8001758/5c70fdb6-0b9b-11e5-9529-c5697738e3fd.png)
这是最大化的效果
![tablec](https://cloud.githubusercontent.com/assets/5020771/8001761/6b736b28-0b9b-11e5-8d45-986783e51a31.png)

**Comment by Minwe** [comment]
我试了一下没有遇到没有还原的情况，不太确定问题出在哪。

**Comment by xfworld** [comment]
@Minwe  我用IE也测试一把，一样的效果..

慢慢改进呗，看我能不能找到问题点

**Comment by miruiSoft** [comment]
查询结果有数千行，能不能每点击下一页，数据都动态在后台获取呢？
