### ISSUE TITLE
Amaze UI 移植插件 DataTables 响应式 文字显示不全，如何解决？

### ISSUE THREAD

**Issue by dabing69221** [amazeui/datatables#11]
Amaze UI 移植插件 DataTables 响应式 文字显示不全，如何解决？ 如下图：
![qq 20160818083154](https://cloud.githubusercontent.com/assets/20959956/17758079/ccdaa5b0-651e-11e6-9757-a0a03c6b5834.png)

**Comment by dabing69221** [comment]
代码如下：
<table width="100%" class="am-table am-table-striped am-table-bordered am-table-compact am-text-nowrap" id="example-r">
    <thead>
       ...
    </thead>
    <tfoot>
      ...
    </tfoot>
    <tbody>
      ...
    </tbody>
<table>

**Comment by minwe** [comment]
加上：

```css
.dtr-data {
  white-space: normal;
}
```

**Comment by dabing69221** [comment]
@minwe 谢谢，问题已解决！
`/*修复datatables显示问题*/
		function repairDataTables() {
			//修复“单元格”文字过长不自动折行问题
			$('.am-text-nowrap').css('white-space','normal');
			$('table.dataTable thead>tr>th').css('padding-right','.4rem');
		}`
