### ISSUE TITLE
怎么实现默认显示所有的数据，不分页呢？

### ISSUE THREAD

**Issue by zuoakang** [amazeui/datatables#18]

**Comment by minwe** [comment]
用相关关键字 Google 一下就知道了：https://www.google.com/search?q=datatables+disable+pagination&oq=datatables+disable+&aqs=chrome.3.0j69i57j0l4.8915j0j1&sourceid=chrome&ie=UTF-8

https://datatables.net/reference/option/paging

```
$('#example').dataTable( {
    "paging": false
});
```

**Comment by zuoakang** [comment]
thx @minwe
