### ISSUE TITLE
这个控件后续还有更新计划么？

### ISSUE THREAD

**Issue by xfworld** [amazeui/datatables#2]
大部分的方法和说明都还没给出来，比如动态加载数据，动态查询绑定，列绑定等等。
还有常用的双击，单击事件

**Comment by meowl** [comment]
可以去官网看看啊https://www.datatables.net，
还有个个人制作的datatables中文站http://dt.thxopen.com/

**Comment by xfworld** [comment]
谢谢 @meowl  
我去看看api
