### ISSUE TITLE
初始化的问题

### ISSUE THREAD

**Issue by xfworld** [amazeui/datatables#3]
如果在document ready的时候，装载和实例化datatable，页面放大和缩小会执行响应式的效果。

如果是在其他的事件执行的状态和实例化，貌似响应式的效果就消失了。如图：

![image](https://cloud.githubusercontent.com/assets/5020771/8075692/ea446ae6-0f75-11e5-9b7a-755dc3491a35.png)
![image](https://cloud.githubusercontent.com/assets/5020771/8075701/00964a62-0f76-11e5-82b4-c13564c92c40.png)
![image](https://cloud.githubusercontent.com/assets/5020771/8075709/119ac90a-0f76-11e5-8c4c-4a76643689a5.png)

**Comment by meowl** [comment]
你试试关掉配置中的自动计算宽度："autoWidth": false,

**Comment by xfworld** [comment]
有效果，但是在table中定义的am-text-nowrap和table上层div定义的am-scrollable-horizontal  没启作用...

比较奇怪..

**Comment by meowl** [comment]
我这里是有效的,lz实在不行你可以贴出代码来看看。
datatables表格最好不要使用am-scrollable-horizontal这个amaze的横向滚动条，显示效果不好，datatables自身是有横向滚动条效果的，"scrollX": true,
另外datatables的横向滚动需要在table上加上am-text-nowrap样式才会生效。

**Comment by xfworld** [comment]
代码很简单，我用了am-scrollable-horizontal这个样式，效果还可以啊。你看看我的代码：
<code>
 <div class="am-text-xs am-scrollable-horizontal" id="warninglist">
							 <table class="am-table am-table-striped am-table-bordered am-table-compact am-table-hover am-table-radius am-text-nowrap" id="warningtable">
									  <thead>
									  <tr>
									    <th>消息</th>
									    <th>技术人员</th>
									    <th>严重程度</th>
									    <th>最后更新时间</th>
									  </tr>
									  </thead>
									  <tbody>
									  <tr>
									    <td>Internet
									      Explorer 4.0</td>
									    <td>Win 95+</td>
									    <td class="center"> 4</td>
									    <td class="center">X</td>
									  </tr>
									  <tr>
									    <td>Internet
									      Explorer 5.0</td>
									    <td>Win 95+</td>
									    <td class="center">5</td>
									    <td class="center">C</td>
									  </tr>
									  <tr>
									    <td>Internet
									      Explorer 5.5</td>
									    <td>Win 95+</td>
									    <td class="center">5.5</td>
									    <td class="center">A</td>
									  </tr>
									  <tr>
									    <td>Internet
									      Explorer 6</td>
									    <td>Win 98+</td>
									    <td class="center">6</td>
									    <td class="center">A</td>
									  </tr>
									  <tr>
									    <td>Internet Explorer 7</td>
									    <td>Win XP SP2+</td>
									    <td class="center">7</td>
									    <td class="center">A</td>
									  </tr>
									  <tr>
									    <td>AOL browser (AOL desktop)</td>
									    <td>Win XP</td>
									    <td class="center">6</td>
									    <td class="center">A</td>
									  </tr>
									  </tbody>
									</table>
								</div>
</code>

唯一不一样的，就是只有在tab在opened的时候在加载和初始化这个datatable...

**Comment by meowl** [comment]
这个是datatables的滚动条效果
![333](https://cloud.githubusercontent.com/assets/1335861/8076712/0901695a-0f82-11e5-8b21-ba2fcefa3f8a.png)

这个是am-scrollable-horizontal的效果
![22](https://cloud.githubusercontent.com/assets/1335861/8076775/96ace5c2-0f82-11e5-90e0-8f017cefe8bc.png)

“只有在tab在opened的时候在加载和初始化这个datatable...”，不太明白lz说的是啥...

**Comment by xfworld** [comment]
我先试试你给的参数..

**Comment by xfworld** [comment]
'retrieve' : true,
是这个参数造成的... 吐血了
问题搞定了

**Comment by xfworld** [comment]
@meowl  datatable的dom参数你一般都怎么处理的？

**Comment by meowl** [comment]
按你的需要来啊，你还是看看文档吧 http://dt.thxopen.com/reference/option/dom.html
