### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by xfworld** [amazeui/datatables#4]
![1](https://cloud.githubusercontent.com/assets/5020771/8515313/ea20f9aa-23d2-11e5-8d80-a3c914ec3860.png)

这个问题，怎么破....

**Comment by Minwe** [comment]
什么浏览器？调下行高试试吧。

**Comment by xfworld** [comment]
手机端呢，我去看看浏览器版本
mozilla/5.0
applewebkit/534.30

**Comment by xfworld** [comment]
@Minwe 下面这个样式可以集成过来不....
http://dt.thxopen.com/example/user_share/yuui.html
