### ISSUE TITLE
Uncaught TypeError: Cannot set property 'oLanguage' of undefined when working with requireJS

### ISSUE THREAD

**Issue by liangjw** [amazeui/datatables#5]
Uncaught TypeError: Cannot set property 'oLanguage' of undefined when working with requireJS !

Is there any proplem with my code?

define(['jquery','datatables'],function($){
    //code here
}

**Comment by minwe** [comment]
加个 `shim` 试试：

```js
requirejs.config({
    paths: {
      '$': 'http://code.jquery.com/jquery-2.1.4.min',
      'datatables': 'http://amazeui.github.io/datatables/amazeui.datatables'
    },
    shim: {
      'datatables': ['$']
    }
  });
```

**Comment by liangjw** [comment]
加了 shim: {'datatables': ['jquery']}
不行，源码里的var DataTable = require('datatables') 这个一直没有返回datatables的对象，
而且源码好像跑了var DataTable = require('datatables'); 才跑define('datatables') 这没有问题？

**Comment by minwe** [comment]
你用的是没有压缩的版本么？试一下 minify 的版本。

**Comment by liangjw** [comment]
两个版本都试过了。

**Comment by liangjw** [comment]
我直接用官方版的datatables是没报错的，问题就出在var DataTable = require('datatables')  这里了

**Comment by minwe** [comment]
Ok，我再看一下。

**Comment by minwe** [comment]
你再试一下。

**Comment by liangjw** [comment]
已经没有问题了，谢谢！
