### ISSUE TITLE
兄台，排序有没有按数字序而不是字典序的方式啊？

### ISSUE THREAD

**Issue by fy0** [amazeui/datatables#8]
我的表格第一栏显示主键。
一开始我导了6个数据在测试，等弄好之后实际导入了200多个数据，发现数据变成了：
1
10
100
...

吓得我赶紧改成了
00001
00002
....

暂时解决了问题，但有没有直接可以支持数字序的选项呢？

**Comment by wohenbushuang** [comment]
同 望修复 暂时通过注释

> DataTable.defaults.oLanguage = {
  sProcessing:   "处理中...",
  sLengthMenu:   "显示 _MENU_ 项结果",
  sZeroRecords:  "没有匹配结果",
  sInfo:         "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
  sInfoEmpty:    "显示第 0 至 0 项结果，共 0 项",
  sInfoFiltered: "(由 _MAX_ 项结果过滤)",
  sInfoPostFix:  "",
  sSearch:       "搜索：",
  sUrl:          "",
  sEmptyTable:     "表中数据为空",
  sLoadingRecords: "载入中...",
  sInfoThousands:  ",",
  oPaginate: {
    sFirst:    "首页",
    sPrevious: "上页",
    sNext:     "下页",
    sLast:     "末页"
  },
  oAria: {
    sSortAscending:  ": 以升序排列此列",
    sSortDescending: ": 以降序排列此列"
  }
};

后再在init时候用datatables的option传入汉化

**Comment by minwe** [comment]
排序功能可以看一下官方文档，这里只是做了适配 Amaze UI 样式的工作，其他功能没有动。

http://amazeui.github.io/datatables/docs/demo.html#zhong-wen-pai-xu

大概就是自己写一个排序的方法，不同列的可以指定相应的排序方法。

**Comment by fy0** [comment]
原来如此 谢了
