### ISSUE TITLE
分页数据的BUG

### ISSUE THREAD

**Issue by xfworld** [amazeui/datatables#9]
![2](https://cloud.githubusercontent.com/assets/5020771/14666316/790c7a10-070b-11e6-9074-1fc7af1dadf9.png)
@minwe 我发现了一个bug，不知道是怎么产生的。

另外我看DataTable官网已经更新版本了，是不是可以直接用新的版本进行替换？

**Comment by minwe** [comment]
你设置什么参数了吗？

应该是能替换的。

**Comment by xfworld** [comment]
默认的，我没做什么配置，能告诉我这块的 功能函数在多少行么？ 我自己跟一下试试；
我发现变量的数据都是对的，就是最后的显示出现了问题；不影响功能...

**Comment by minwe** [comment]
已经升级到 DateTables 最新版了，你可以重新下载试一下。

**Comment by xfworld** [comment]
好，我试试

**Comment by xfworld** [comment]
@minwe 问题找到了，坑爹的代码
`"fnFormatNumber": function ( toFormat ) {
			return toFormat.toString().replace(
				/\B(?=(\d{3})+(?!\d))/g,
				this.oLanguage.sThousands
			);
		},`
貌似就是这个this.oLanguage.sThousands 属性找不到，所以在里面会有undefined的情况

**Comment by xfworld** [comment]
@minwe  你在定义默认语言的时候，咋把千分位干掉了....  让我吐个血....

**Comment by minwe** [comment]
`sInfoThousands` 还是哪个？

**Comment by xfworld** [comment]
默认的是this.oLanguage.sThousands
你定义的是sInfoThousands 
但是在fnFormatNumber方法里面，没有调整过来...

**Comment by xfworld** [comment]
来吧，在发个版本吧.... ^_^

**Comment by minwe** [comment]
```javascript
// Old parameter name of the thousands separator mapped onto the new
if ( lang.sInfoThousands ) {
  lang.sThousands = lang.sInfoThousands;
}
```

插件内部有处理的，没正确显示出来？

**Comment by xfworld** [comment]
嗯，直接调用原有的内联方法了...

**Comment by minwe** [comment]
你下载刚 传上去的试试吧

**Comment by xfworld** [comment]
直接加了个属性啊，我晕，我试试

**Comment by xfworld** [comment]
@minwe 测试通过：）

另外请教一下，如果用jquery，用什么前端框架做SPA好一点。 团队的兄弟们太弱了，我不敢上ES6的东西.....

**Comment by minwe** [comment]
jQuery 其实只有一个工具，任何框架都可以跟 jQuery 一起用。

Backbone 貌似就是绑定 jQuery 的，[T3.js](http://t3js.org/) 也可以看看。

没法明确告诉你选哪个框架，你可以从以下几个方面考虑选择：

- 学习曲线：通过短期培训学习能否让团队成员掌握；
- 社区成熟程度：项目是否及时维护更新，是否有足够多的第三方插件；
- 中文资料丰富程度：如果团队语言能力跟不上，那还得考虑是否有足够多的中文资料。

**Comment by xfworld** [comment]
收到
